leftnav:
- identifier: 837573eb-dba2-fddb-deeb-36a1cf0643f1
  name: Syllabus
  url: /pages/syllabus
  weight: 10
- identifier: ba9cc8fb-d134-9df5-6932-857aeccc0141
  name: Readings
  url: /pages/readings
  weight: 20
- identifier: 956c0b50-de80-15b2-ef2a-96cfdf39519b
  name: Lecture Notes
  url: /pages/lecture-notes
  weight: 30
- identifier: 68ae0f1c-7e34-8a83-049d-c26ed7086302
  name: Assignments
  url: /pages/assignments
  weight: 40
- identifier: dc407be1-10d5-201b-a779-448c753389a6
  name: Study Materials
  url: /pages/study-materials
  weight: 50
